name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    name: OTP 28 / Elixir 1.18.4
    env:
      POSTGRES_USER: postgres
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 28
          elixir-version: 1.18.4
      - run: mix deps.get
      - run: mix assets.build
      - run: mix test
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Gigalixir
        env:
          GIGALIXIR_EMAIL: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}
          GIGALIXIR_APP_NAME: ${{ secrets.GIGALIXIR_APP_NAME }}
        run: |
          EMAIL_ENCODED=$(echo "$GIGALIXIR_EMAIL" | sed 's/@/%40/g')
          git remote add gigalixir https://$EMAIL_ENCODED:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
          git push gigalixir main
  terraform:
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_grafana_auth: ${{ secrets.GRAFANA_AUTH }}
      TF_VAR_metrics_bearer_token: ${{ secrets.METRICS_BEARER_TOKEN }}
      TF_VAR_base_url: ${{ vars.BASE_URL }}
      TF_ACCESS_KEY: ${{ secrets.TF_ACCESS_KEY }}
      TF_SECRET_KEY: ${{ secrets.TF_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Wait for /metrics
        uses: emilioschepis/wait-for-endpoint@v1.0.3
        with:
          url: "${{ vars.BASE_URL }}/metrics"
          method: GET
          expected-status: 200
          timeout: 120000
          interval: 5000
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=$TF_ACCESS_KEY" \
            -backend-config="secret_key=$TF_SECRET_KEY"
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan -out=tfplan
      - name: Terraform Apply
        run: terraform apply tfplan
